spring:
  application:
    name: task_app
  datasource:
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    database: ${JPA_DATABASE:h2}
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
    defer-datasource-initialization: true
logging:
  file:
    name: app.log
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}

